# mcl_2d:
#   ros__parameters:
#     param_name: UAAAAAAAAAAAAAAAAAAAAAAAAAAA!!
#     # 他のパラメータをここに追加

/**:
  ros__parameters:
    global_frame_id: "map"
    footprint_frame_id: "base_footprint"
    odom_frame_id: "odom"
    base_frame_id : "base_link"
    odom_freq: 10
    initial_pose:
      - 0.0  # x
      - 2.0  # y
      - 0.0  # yaw
    particles_num: 50
    odom_convariance:
      - 0.01   #回転成分から生まれる回転成分のズレ.
      - 0.01   #並進成分から生まれる回転成分のズレ
      - 0.01   #並進成分から生まれる並進成分のズレ
      - 0.01   #回転成分から生まれる並進成分のズレ
      - 0.01
      - 0.01